### PR TITLE
Makes use of mysql includedir for easier updating

### PR DESCRIPTION
**Pull request by ed-**
The password writing process is much easier now that we don't have to use a temp file and copy it over sans password.

### CODE REVIEW

**Comment by jcru** [comment]
+1

**Comment by cp16net** [comment]
+1

**Comment by TimSimpsonR** [comment]
+1

**Comment by ed-** [comment]
17 days ago

# DISAPPOINTED

http://youtu.be/_O1hM-k3aUY?t=9s

**Pull request merged**
